export const GET_CACHE_REQUEST = "GET_CACHE_REQUEST";
export const GET_CACHE_SUCCESS = "GET_CACHE_SUCCESS";
export const GET_CACHE_FAILURE = "GET_CACHE_FAILURE";
export const GET_CACHE_FROM_LOCAL = "GET_CACHE_FROM_LOCAL";

export const GET_CACHE_USER_FUNCTION_LIST = "ERPUSERCACHE.FUNCTION";

export const USER_PERMISSION_VIEW = "USER_PERMISSION_VIEW";

// lý do hủy giao hàng
export const CANCELDELIVERYREASON_VIEW = "CANCELDELIVERYREASON_VIEW";
export const CANCELDELIVERYREASON_ADD = "CANCELDELIVERYREASON_ADD";
export const CANCELDELIVERYREASON_UPDATE = "CANCELDELIVERYREASON_UPDATE";
export const CANCELDELIVERYREASON_DELETE = "CANCELDELIVERYREASON_DELETE";

// loại phương tiện vận chuyển
export const CARRIERTYPE_VIEW = "CARRIERTYPE_VIEW";
export const CARRIERTYPE_ADD = "CARRIERTYPE_ADD";
export const CARRIERTYPE_UPDATE = "CARRIERTYPE_UPDATE";
export const CARRIERTYPE_DELETE = "CARRIERTYPE_DELETE";

// loại giấy tờ tùy thân
export const IDDOCUMENTTYPE_VIEW = "IDDOCUMENTTYPE_VIEW";
export const IDDOCUMENTTYPE_ADD = "IDDOCUMENTTYPE_ADD";
export const IDDOCUMENTTYPE_UPDATE = "IDDOCUMENTTYPE_UPDATE";
export const IDDOCUMENTTYPE_DELETE = "IDDOCUMENTTYPE_DELETE";

// gói sản phẩm lắp đặt kèm theo
export const INSTALLBUNDLE_VIEW = "INSTALLBUNDLE_VIEW";
export const INSTALLBUNDLE_ADD = "INSTALLBUNDLE_ADD";
export const INSTALLBUNDLE_UPDATE = "INSTALLBUNDLE_UPDATE";
export const INSTALLBUNDLE_DELETE = "INSTALLBUNDLE_DELETE";

// nhóm sản phẩm cần vật tư lắp đặt
export const INSTALLMATERIAL_VIEW = "INSTALLMATERIAL_VIEW";
export const INSTALLMATERIAL_ADD = "INSTALLMATERIAL_ADD";
export const INSTALLMATERIAL_UPDATE = "INSTALLMATERIAL_UPDATE";
export const INSTALLMATERIAL_DELETE = "INSTALLMATERIAL_DELETE";

// loại đóng gói hàng hóa vận chuyển
export const PACKAGETYPE_VIEW = "PACKAGETYPE_VIEW";
export const PACKAGETYPE_ADD = "PACKAGETYPE_ADD";
export const PACKAGETYPE_UPDATE = "PACKAGETYPE_UPDATE";
export const PACKAGETYPE_DELETE = "PACKAGETYPE_DELETE";

// đối tác
export const PARTNER_VIEW = "PARTNER_VIEW";
export const PARTNER_ADD = "PARTNER_ADD";
export const PARTNER_UPDATE = "PARTNER_UPDATE";
export const PARTNER_DELETE = "PARTNER_DELETE";

// quyền nhà cung cấp
export const PARTNERPRIVILEDGE_VIEW = "PARTNERPRIVILEDGE_VIEW";
export const PARTNERPRIVILEDGE_ADD = "PARTNERPRIVILEDGE_ADD";
export const PARTNERPRIVILEDGE_UPDATE = "PARTNERPRIVILEDGE_UPDATE";
export const PARTNERPRIVILEDGE_DELETE = "PARTNERPRIVILEDGE_DELETE";

// nhóm quyền nhà cung cấp
export const PARTNERPRIVILEDGEGROUP_VIEW = "PARTNERPRIVILEDGEGROUP_VIEW";
export const PARTNERPRIVILEDGEGROUP_ADD = "PARTNERPRIVILEDGEGROUP_ADD";
export const PARTNERPRIVILEDGEGROUP_UPDATE = "PARTNERPRIVILEDGEGROUP_UPDATE";
export const PARTNERPRIVILEDGEGROUP_DELETE = "PARTNERPRIVILEDGEGROUP_DELETE";

// vai trò người dùng của nhà cung cấp
export const PARTNERROLE_VIEW = "PARTNERROLE_VIEW";
export const PARTNERROLE_ADD = "PARTNERROLE_ADD";
export const PARTNERROLE_UPDATE = "PARTNERROLE_UPDATE";
export const PARTNERROLE_DELETE = "PARTNERROLE_DELETE";

// người dùng của nhà cung cấp
export const PARTNERUSER_VIEW = "PARTNERUSER_VIEW";
export const PARTNERUSER_ADD = "PARTNERUSER_ADD";
export const PARTNERUSER_UPDATE = "PARTNERUSER_UPDATE";
export const PARTNERUSER_DELETE = "PARTNERUSER_DELETE";

// loại hợp đồng dịch vụ
export const SERVICEAGREEMENTTYPE_VIEW = "SERVICEAGREEMENTTYPE_VIEW";
export const SERVICEAGREEMENTTYPE_ADD = "SERVICEAGREEMENTTYPE_ADD";
export const SERVICEAGREEMENTTYPE_UPDATE = "SERVICEAGREEMENTTYPE_UPDATE";
export const SERVICEAGREEMENTTYPE_DELETE = "SERVICEAGREEMENTTYPE_DELETE";

// loại mùa dịch vụ
export const SERVICESEASONTYPE_VIEW = "SERVICESEASONTYPE_VIEW";
export const SERVICESEASONTYPE_ADD = "SERVICESEASONTYPE_ADD";
export const SERVICESEASONTYPE_UPDATE = "SERVICESEASONTYPE_UPDATE";
export const SERVICESEASONTYPE_DELETE = "SERVICESEASONTYPE_DELETE";

// loại dịch vụ
export const SERVICETYPE_VIEW = "SERVICETYPE_VIEW";
export const SERVICETYPE_ADD = "SERVICETYPE_ADD";
export const SERVICETYPE_UPDATE = "SERVICETYPE_UPDATE";
export const SERVICETYPE_DELETE = "SERVICETYPE_DELETE";

// phương thức thanh toán chi phí vận chuyển
export const SHIPMENTFEEPAYMENTMETHOD_VIEW = "SHIPMENTFEEPAYMENTMETHOD_VIEW";
export const SHIPMENTFEEPAYMENTMETHOD_ADD = "SHIPMENTFEEPAYMENTMETHOD_ADD";
export const SHIPMENTFEEPAYMENTMETHOD_UPDATE = "SHIPMENTFEEPAYMENTMETHOD_UPDATE";
export const SHIPMENTFEEPAYMENTMETHOD_DELETE = "SHIPMENTFEEPAYMENTMETHOD_DELETE";

// loại phí vận chuyển
export const SHIPMENTFEETYPE_VIEW = "SHIPMENTFEETYPE_VIEW";
export const SHIPMENTFEETYPE_ADD = "SHIPMENTFEETYPE_ADD";
export const SHIPMENTFEETYPE_UPDATE = "SHIPMENTFEETYPE_UPDATE";
export const SHIPMENTFEETYPE_DELETE = "SHIPMENTFEETYPE_DELETE";

// loại hàng hóa vận chuyển
export const SHIPMENTGOODSTYPE_VIEW = "SHIPMENTGOODSTYPE_VIEW";
export const SHIPMENTGOODSTYPE_ADD = "SHIPMENTGOODSTYPE_ADD";
export const SHIPMENTGOODSTYPE_UPDATE = "SHIPMENTGOODSTYPE_UPDATE";
export const SHIPMENTGOODSTYPE_DELETE = "SHIPMENTGOODSTYPE_DELETE";

//nhóm trạng thái yêu cầu vận chuyển
export const SHIPMENTORDERSTATUSGROUP_VIEW = "SHIPMENTORDERSTATUSGROUP_VIEW";
export const SHIPMENTORDERSTATUSGROUP_ADD = "SHIPMENTORDERSTATUSGROUP_ADD";
export const SHIPMENTORDERSTATUSGROUP_UPDATE = "SHIPMENTORDERSTATUSGROUP_UPDATE";
export const SHIPMENTORDERSTATUSGROUP_DELETE = "SHIPMENTORDERSTATUSGROUP_DELETE";

// trạng thái yêu cầu vận chuyển
export const SHIPMENTORDERSTATUS_VIEW = "SHIPMENTORDERSTATUS_VIEW";
export const SHIPMENTORDERSTATUS_ADD = "SHIPMENTORDERSTATUS_ADD";
export const SHIPMENTORDERSTATUS_UPDATE = "SHIPMENTORDERSTATUS_UPDATE";
export const SHIPMENTORDERSTATUS_DELETE = "SHIPMENTORDERSTATUS_DELETE";

// bước xử lý yêu cầu vận chuyển
export const SHIPMENTORDERSTEP_VIEW = "SHIPMENTORDERSTEP_VIEW";
export const SHIPMENTORDERSTEP_ADD = "SHIPMENTORDERSTEP_ADD";
export const SHIPMENTORDERSTEP_UPDATE = "SHIPMENTORDERSTEP_UPDATE";
export const SHIPMENTORDERSTEP_DELETE = "SHIPMENTORDERSTEP_DELETE";

// loại dịch vụ vận chuyển
export const SHIPMENTSERVICETYPE_VIEW = "SHIPMENTSERVICETYPE_VIEW";
export const SHIPMENTSERVICETYPE_ADD = "SHIPMENTSERVICETYPE_ADD";
export const SHIPMENTSERVICETYPE_UPDATE = "SHIPMENTSERVICETYPE_UPDATE";
export const SHIPMENTSERVICETYPE_DELETE = "SHIPMENTSERVICETYPE_DELETE";

// loại đối tác
export const PARTNERTYPE_VIEW = "PARTNERTYPE_VIEW";
export const PARTNERTYPE_ADD = "PARTNERTYPE_ADD";
export const PARTNERTYPE_UPDATE = "PARTNERTYPE_UPDATE";
export const PARTNERTYPE_DELETE = "PARTNERTYPE_DELETE";

// loại yêu cầu vận chuyển
export const SHIPMENTORDERTYPE_VIEW = "SHIPMENTORDERTYPE_VIEW";
export const SHIPMENTORDERTYPE_ADD = "SHIPMENTORDERTYPE_ADD";
export const SHIPMENTORDERTYPE_UPDATE = "SHIPMENTORDERTYPE_UPDATE";
export const SHIPMENTORDERTYPE_DELETE = "SHIPMENTORDERTYPE_DELETE";

// yêu cầu vận chuyển
export const SHIPMENTORDER_VIEW = "SHIPMENTORDER_VIEW";
export const SHIPMENTORDER_ADD = "SHIPMENTORDER_ADD";
export const SHIPMENTORDER_UPDATE = "SHIPMENTORDER_UPDATE";
export const SHIPMENTORDER_DELETE = "SHIPMENTORDER_DELETE";
export const SHIPMENTORDER_EXPECTEDDELIVERYDATE = "SHIPMENTORDER_EXPECTEDDELIVERYDATE";

// hợp đồng dịch vụ
export const SERVICEAGREEMENT_VIEW = "SERVICEAGREEMENT_VIEW";
export const SERVICEAGREEMENT_ADD = "SERVICEAGREEMENT_ADD";
export const SERVICEAGREEMENT_UPDATE = "SERVICEAGREEMENT_UPDATE";
export const SERVICEAGREEMENT_DELETE = "SERVICEAGREEMENT_DELETE";

// Phụ lục biểu phí
export const FEEAPPENDIX_VIEW = "FEEAPPENDIX_VIEW";
export const FEEAPPENDIX_ADD = "FEEAPPENDIX_ADD";
export const FEEAPPENDIX_UPDATE = "FEEAPPENDIX_UPDATE";
export const FEEAPPENDIX_DELETE = "FEEAPPENDIX_DELETE";

// Phụ lục biểu phí
export const ABILITI_VIEW = "ABILITI_VIEW";
export const ABILITI_ADD = "ABILITI_ADD";
export const ABILITI_UPDATE = "ABILITI_UPDATE";
export const ABILITI_DELETE = "ABILITI_DELETE";

// Chi tiết phụ lục biểu phí
export const FEEAPPENDIXDETAIL_VIEW = "FEEAPPENDIXDETAIL_VIEW";
export const FEEAPPENDIXDETAIL_ADD = "FEEAPPENDIXDETAIL_ADD";
export const FEEAPPENDIXDETAIL_UPDATE = "FEEAPPENDIXDETAIL_UPDATE";
export const FEEAPPENDIXDETAIL_DELETE = "FEEAPPENDIXDETAIL_DELETE";

// Định nghĩa kho điều phối giao hàng

export const COORDINATORSTORE_VIEW = "COORDINATORSTORE_VIEW";
export const COORDINATORSTORE_ADD = "COORDINATORSTORE_ADD";
export const COORDINATORSTORE_UPDATE = "COORDINATORSTORE_UPDATE";
export const COORDINATORSTORE_DELETE = "COORDINATORSTORE_DELETE";

// thông tin giao dịch với đối tác
export const PARTNERTRANSACTION_VIEW = "PARTNERTRANSACTION_VIEW";

// nhật ký gọi api
export const APICALLLOG_VIEW = "APICALLLOG_VIEW";

//Nhật ký tính thưởng
export const REWARDCOMPUTELOG_VIEW = "REWARDCOMPUTELOG_VIEW";

// yêu cầu tạm ứng
export const ADVANCEREQUEST_VIEW = "ADVANCEREQUEST_VIEW";

// kỹ năng
export const SKILL_VIEW = "SKILL_VIEW";
export const SKILL_ADD = "SKILL_ADD";
export const SKILL_UPDATE = "SKILL_UPDATE";
export const SKILL_DELETE = "SKILL_DELETE";

// danh mục kỹ năng
export const SKILLCATEGORY_VIEW = "SKILLCATEGORY_VIEW";
export const SKILLCATEGORY_ADD = "SKILLCATEGORY_ADD";
export const SKILLCATEGORY_UPDATE = "SKILLCATEGORY_UPDATE";
export const SKILLCATEGORY_DELETE = "SKILLCATEGORY_DELETE";

// cấp bậc kỹ năng
export const SKILLRANK_VIEW = "SKILLRANK_VIEW";
export const SKILLRANK_ADD = "SKILLRANK_ADD";
export const SKILLRANK_UPDATE = "SKILLRANK_UPDATE";
export const SKILLRANK_DELETE = "SKILLRANK_DELETE";

// Danh sách xe
export const VEHICLE_VIEW = "VEHICLE_VIEW";
export const VEHICLE_ADD = "VEHICLE_ADD";
export const VEHICLE_UPDATE = "VEHICLE_UPDATE";
export const VEHICLE_DELETE = "VEHICLE_DELETE";

// Danh sách trạng thái hoạt động của phương tiện
export const VEHICLEACITIVITYSTATUS_VIEW = 'VEHICLEACITIVITYSTATUS_VIEW';
export const VEHICLEACITIVITYSTATUS_ADD = 'VEHICLEACITIVITYSTATUS_ADD';
export const VEHICLEACITIVITYSTATUS_UPDATE = 'VEHICLEACITIVITYSTATUS_UPDATE';
export const VEHICLEACITIVITYSTATUS_DELETE = 'VEHICLEACITIVITYSTATUS_DELETE';

// Danh sách thuê
export const RENTALTYPE_VIEW = 'RENTALTYPE_VIEW';
export const RENTALTYPE_ADD = 'RENTALTYPE_ADD';
export const RENTALTYPE_UPDATE = 'RENTALTYPE_UPDATE';
export const RENTALTYPE_DELETE = 'RENTALTYPE_DELETE';

// Ca làm việc
export const WORKINGSHIFT_VIEW = "WORKINGSHIFT_VIEW";
export const WORKINGSHIFT_ADD = "WORKINGSHIFT_ADD";
export const WORKINGSHIFT_UPDATE = "WORKINGSHIFT_UPDATE";
export const WORKINGSHIFT_DELETE = "WORKINGSHIFT_DELETE";

// Phân ca làm việc của nhân viên
export const WORKINGPLAN_VIEW = "WORKINGPLAN_VIEW";
export const WORKINGPLAN_ADD = "WORKINGPLAN_ADD";
export const WORKINGPLAN_UPDATE = "WORKINGPLAN_UPDATE";
export const WORKINGPLAN_DELETE = "WORKINGPLAN_DELETE";

// loại khu vực
export const AREATYPE_VIEW = "AREATYPE_VIEW";
export const AREATYPE_ADD = "AREATYPE_ADD";
export const AREATYPE_UPDATE = "AREATYPE_UPDATE";
export const AREATYPE_DELETE = "AREATYPE_DELETE";

// khu vực
export const AREA_VIEW = "AREA_VIEW";
export const AREA_ADD = "AREA_ADD";
export const AREA_UPDATE = "AREA_UPDATE";
export const AREA_DELETE = "AREA_DELETE";

// kỹ năng của nhân viên
export const USERSKILL_VIEW = "USERSKILL_VIEW";
export const USERSKILL_ADD = "USERSKILL_ADD";
export const USERSKILL_UPDATE = "USERSKILL_UPDATE";
export const USERSKILL_DELETE = "USERSKILL_DELETE";

//xuất danh sách kỹ năng của nhân viên
export const USERSKILL_EXPORT = "USERSKILL_EXPORT";

// Nhóm vật tư lắp đặt
export const MATERIALGROUP_VIEW = "MATERIALGROUP_VIEW";
export const MATERIALGROUP_ADD = "MATERIALGROUP_ADD";
export const MATERIALGROUP_UPDATE = "MATERIALGROUP_UPDATE";
export const MATERIALGROUP_DELETE = "MATERIALGROUP_DELETE";

// Nhóm danh sách tiền phải trả cho nhà cung cấp dịch vụ theo ngày
export const PARTNERPAYABLE_VIEW = "PARTNERPAYABLE_VIEW";
export const PARTNERPAYABLE_ADD = "PARTNERPAYABLE_ADD";
export const PARTNERPAYABLE_UPDATE = "PARTNERPAYABLE_UPDATE";
export const PARTNERPAYABLE_DELETE = "PARTNERPAYABLE_DELETE";

// Nhóm danh sách chi tiết tiền phải trả cho nhà cung cấp dịch vụ
export const PARTNERPAYABLEDETAIL_VIEW = "PARTNERPAYABLEDETAIL_VIEW";
export const PARTNERPAYABLEDETAIL_ADD = "PARTNERPAYABLEDETAIL_ADD";
export const PARTNERPAYABLEDETAIL_UPDATE = "PARTNERPAYABLEDETAIL_UPDATE";
export const PARTNERPAYABLEDETAIL_DELETE = "PARTNERPAYABLEDETAIL_DELETE";

// Loại giới hạn
export const LIMITTYPE_VIEW = "LIMITTYPE_VIEW";
export const LIMITTYPE_ADD = "LIMITTYPE_ADD";
export const LIMITTYPE_UPDATE = "LIMITTYPE_UPDATE";
export const LIMITTYPE_DELETE = "LIMITTYPE_DELETE";

// Bảng khai báo giới hạn theo người dùng
export const USER_LIMIT_VIEW = "USER_LIMIT_VIEW";
export const USER_LIMIT_ADD = "USER_LIMIT_ADD";
export const USER_LIMIT_UPDATE = "USER_LIMIT_UPDATE";
export const USER_LIMIT_DELETE = "USER_LIMIT_DELETE";

//Loại yêu cầu tạm ứng
export const ADVANCEREQUESTTYPE_VIEW = "ADVANCEREQUESTTYPE_VIEW";
export const ADVANCEREQUESTTYPE_ADD = "ADVANCEREQUESTTYPE_ADD";
export const ADVANCEREQUESTTYPE_UPDATE = "ADVANCEREQUESTTYPE_UPDATE";
export const ADVANCEREQUESTTYPE_DELETE = "ADVANCEREQUESTTYPE_DELETE";

//Loại yêu cầu hủy vật tư
export const DESTROYREQUESTTYPE_VIEW = "DESTROYREQUESTTYPE_VIEW";
export const DESTROYREQUESTTYPE_ADD = "DESTROYREQUESTTYPE_ADD";
export const DESTROYREQUESTTYPE_UPDATE = "DESTROYREQUESTTYPE_UPDATE";
export const DESTROYREQUESTTYPE_DELETE = "DESTROYREQUESTTYPE_DELETE";

//Loại yêu cầu kiểm kê
export const INVENTORYREQUESTTYPE_VIEW = "INVENTORYREQUESTTYPE_VIEW";
export const INVENTORYREQUESTTYPE_ADD = "INVENTORYREQUESTTYPE_ADD";
export const INVENTORYREQUESTTYPE_UPDATE = "INVENTORYREQUESTTYPE_UPDATE";
export const INVENTORYREQUESTTYPE_DELETE = "INVENTORYREQUESTTYPE_DELETE";

//Yêu cầu hủy vật tư
export const DESTROYREQUEST_VIEW = "DESTROYREQUEST_VIEW";
export const DESTROYREQUEST_ADD = "DESTROYREQUEST_ADD";
export const DESTROYREQUEST_UPDATE = "DESTROYREQUEST_UPDATE";
export const DESTROYREQUEST_DELETE = "DESTROYREQUEST_DELETE";

//Yêu cầu kiểm kê
export const INVENTORYREQUEST_VIEW = "INVENTORYREQUEST_VIEW";
export const INVENTORYREQUEST_ADD = "INVENTORYREQUEST_ADD";
export const INVENTORYREQUEST_UPDATE = "INVENTORYREQUEST_UPDATE";
export const INVENTORYREQUEST_DELETE = "INVENTORYREQUEST_DELETE";

//Loại yêu cầu nhập trả vật tư
export const MTRETURNREQUESTTYPE_VIEW = "MTRETURNREQUESTTYPE_VIEW";
export const MTRETURNREQUESTTYPE_ADD = "MTRETURNREQUESTTYPE_ADD";
export const MTRETURNREQUESTTYPE_UPDATE = "MTRETURNREQUESTTYPE_UPDATE";
export const MTRETURNREQUESTTYPE_DELETE = "MTRETURNREQUESTTYPE_DELETE";

//Loại thưởng
export const REWARDTYPE_VIEW = "REWARDTYPE_VIEW";
export const REWARDTYPE_ADD = "REWARDTYPE_ADD";
export const REWARDTYPE_UPDATE = "REWARDTYPE_UPDATE";
export const REWARDTYPE_DELETE = "REWARDTYPE_DELETE";

//Loại đơn giá thưởng
export const REWARDPRICETYPE_VIEW = "REWARDPRICETYPE_VIEW";
export const REWARDPRICETYPE_ADD = "REWARDPRICETYPE_ADD";
export const REWARDPRICETYPE_UPDATE = "REWARDPRICETYPE_UPDATE";
export const REWARDPRICETYPE_DELETE = "REWARDPRICETYPE_DELETE";

//Vị trí thưởng
export const REWARDPOSITION_VIEW = "REWARDPOSITION_VIEW";
export const REWARDPOSITION_ADD = "REWARDPOSITION_ADD";
export const REWARDPOSITION_UPDATE = "REWARDPOSITION_UPDATE";
export const REWARDPOSITION_DELETE = "REWARDPOSITION_DELETE";

//Vị trí thưởng theo khoảng thời gian
export const PERIODUSERRWPOSITION_VIEW = "PERIODUSERRWPOSITION_VIEW";
export const PERIODUSERRWPOSITION_ADD = "PERIODUSERRWPOSITION_ADD";
export const PERIODUSERRWPOSITION_UPDATE = "PERIODUSERRWPOSITION_UPDATE";
export const PERIODUSERRWPOSITION_DELETE = "PERIODUSERRWPOSITION_DELETE";

//Loại thưởng của một vị trí thưởng
export const REWARDPOSITION_REWARDTYPE_VIEW = "REWARDPOSITION_REWARDTYPE_VIEW";
export const REWARDPOSITION_REWARDTYPE_ADD = "REWARDPOSITION_REWARDTYPE_ADD";
export const REWARDPOSITION_REWARDTYPE_UPDATE = "REWARDPOSITION_REWARDTYPE_UPDATE";
export const REWARDPOSITION_REWARDTYPE_DELETE = "REWARDPOSITION_REWARDTYPE_DELETE";

//Vị trí thưởng của 1 nhân viên
export const USER_REWARDPOSITION_VIEW = "USER_REWARDPOSITION_VIEW";
export const USER_REWARDPOSITION_ADD = "USER_REWARDPOSITION_ADD";
export const USER_REWARDPOSITION_UPDATE = "USER_REWARDPOSITION_UPDATE";
export const USER_REWARDPOSITION_DELETE = "USER_REWARDPOSITION_DELETE";

//kho thưởng của nhân viên quản lý
export const USER_REWARD_STORE_VIEW = "USER_REWARD_STORE_VIEW";
export const USER_REWARD_STORE_ADD = "USER_REWARD_STORE_ADD";
export const USER_REWARD_STORE_UPDATE = "USER_REWARD_STORE_UPDATE";
export const USER_REWARD_STORE_DELETE = "USER_REWARD_STORE_DELETE";

// bảng giá nhiên liệu
export const FUELPRICE_VIEW = "FUELPRICE_VIEW";
export const FUELPRICE_ADD = "FUELPRICE_ADD";
export const FUELPRICE_UPDATE = "FUELPRICE_UPDATE";
export const FUELPRICE_DELETE = "FUELPRICE_DELETE";

// Lịch tính thưởng
export const REWARDCOMPUTESCHEDULE_VIEW = "REWARDCOMPUTESCHEDULE_VIEW";
export const REWARDCOMPUTESCHEDULE_ADD = "REWARDCOMPUTESCHEDULE_ADD";
export const REWARDCOMPUTESCHEDULE_UPDATE = "REWARDCOMPUTESCHEDULE_UPDATE";
export const REWARDCOMPUTESCHEDULE_DELETE = "REWARDCOMPUTESCHEDULE_DELETE";

//Bảng đơn giá thưởng giao hàng và lắp đặt

export const REWARDPRICETABLE_VIEW = "REWARDPRICETABLE_VIEW";
export const REWARDPRICETABLE_ADD = "REWARDPRICETABLE_ADD";
export const REWARDPRICETABLE_UPDATE = "REWARDPRICETABLE_UPDATE";
export const REWARDPRICETABLE_DELETE = "REWARDPRICETABLE_DELETE";

//Bảng đơn giá thưởng giao hàng và lắp đặt

export const REWARDPRICETABLEDETAIL_VIEW = "REWARDPRICETABLEDETAIL_VIEW";
export const REWARDPRICETABLEDETAIL_ADD = "REWARDPRICETABLEDETAIL_ADD";
export const REWARDPRICETABLEDETAIL_UPDATE = "REWARDPRICETABLEDETAIL_UPDATE";
export const REWARDPRICETABLEDETAIL_DELETE = "REWARDPRICETABLEDETAIL_DELETE";

//Bảng đơn giá thưởng giao hàng và lắp đặt ngoại lệ

export const REWARDPRICETABLE_EXCEPTION_VIEW = "REWARDPRICETABLE_EXCEPTION_VIEW";
export const REWARDPRICETABLE_EXCEPTION_ADD = "REWARDPRICETABLE_EXCEPTION_ADD";
export const REWARDPRICETABLE_EXCEPTION_UPDATE = "REWARDPRICETABLE_EXCEPTION_UPDATE";
export const REWARDPRICETABLE_EXCEPTION_DELETE = "REWARDPRICETABLE_EXCEPTION_DELETE";

//Danh sách tập tin đính kèm yêu cầu hủy vật tư

export const DESTROYREQUEST_ATTACHMENT_VIEW = "DESTROYREQUEST_ATTACHMENT_VIEW";
export const DESTROYREQUEST_ATTACHMENT_ADD = "DESTROYREQUEST_ATTACHMENT_ADD";
export const DESTROYREQUEST_ATTACHMENT_UPDATE = "DESTROYREQUEST_ATTACHMENT_UPDATE";
export const DESTROYREQUEST_ATTACHMENT_DELETE = "DESTROYREQUEST_ATTACHMENT_DELETE";

//Danh sách bình luận của một yêu cầu hủy vật tư

export const DESTROYREQUEST_COMMENT_VIEW = "DESTROYREQUEST_COMMENT_VIEW";
export const DESTROYREQUEST_COMMENT_ADD = "DESTROYREQUEST_COMMENT_ADD";
export const DESTROYREQUEST_COMMENT_UPDATE = "DESTROYREQUEST_COMMENT_UPDATE";
export const DESTROYREQUEST_COMMENT_DELETE = "DESTROYREQUEST_COMMENT_DELETE";

//Loại lắp đặt
export const SHIPMENTSETUPTYPE_VIEW = "SHIPMENTSETUPTYPE_VIEW";
export const SHIPMENTSETUPTYPE_ADD = "SHIPMENTSETUPTYPE_ADD";
export const SHIPMENTSETUPTYPE_UPDATE = "SHIPMENTSETUPTYPE_UPDATE";
export const SHIPMENTSETUPTYPE_DELETE = "SHIPMENTSETUPTYPE_DELETE";

// danh mục phản hồi
export const APPFEEDBACKCATEGORY_VIEW = "APPFEEDBACKCATEGORY_VIEW";
export const APPFEEDBACKCATEGORY_ADD = "APPFEEDBACKCATEGORY_ADD";
export const APPFEEDBACKCATEGORY_UPDATE = "APPFEEDBACKCATEGORY_UPDATE";
export const APPFEEDBACKCATEGORY_DELETE = "APPFEEDBACKCATEGORY_DELETE";

// phân loại phản hồi
export const APPFEEDBACKGROUP_VIEW = "APPFEEDBACKGROUP_VIEW";
export const APPFEEDBACKGROUP_ADD = "APPFEEDBACKGROUP_ADD";
export const APPFEEDBACKGROUP_UPDATE = "APPFEEDBACKGROUP_UPDATE";
export const APPFEEDBACKGROUP_DELETE = "APPFEEDBACKGROUP_DELETE";

// Quyền trên phản hồi
export const APPFEEDBACKPERMISSION_VIEW = "APPFEEDBACKPERMISSION_VIEW";
export const APPFEEDBACKPERMISSION_ADD = "APPFEEDBACKPERMISSION_ADD";
export const APPFEEDBACKPERMISSION_UPDATE = "APPFEEDBACKPERMISSION_UPDATE";
export const APPFEEDBACKPERMISSION_DELETE = "APPFEEDBACKPERMISSION_DELETE";

// độ ưu tiên phản hồi
export const APPFEEDBACKPRIORITY_VIEW = "APPFEEDBACKPRIORITY_VIEW";
export const APPFEEDBACKPRIORITY_ADD = "APPFEEDBACKPRIORITY_ADD";
export const APPFEEDBACKPRIORITY_UPDATE = "APPFEEDBACKPRIORITY_UPDATE";
export const APPFEEDBACKPRIORITY_DELETE = "APPFEEDBACKPRIORITY_DELETE";

// chất lượng xử lý phản hồi
export const APPFEEDBACKQUALITY_VIEW = "APPFEEDBACKQUALITY_VIEW";
export const APPFEEDBACKQUALITY_ADD = "APPFEEDBACKQUALITY_ADD";
export const APPFEEDBACKQUALITY_UPDATE = "APPFEEDBACKQUALITY_UPDATE";
export const APPFEEDBACKQUALITY_DELETE = "APPFEEDBACKQUALITY_DELETE";

// trạng thái phản hồi
export const APPFEEDBACKSTATUS_VIEW = "APPFEEDBACKSTATUS_VIEW";
export const APPFEEDBACKSTATUS_ADD = "APPFEEDBACKSTATUS_ADD";
export const APPFEEDBACKSTATUS_UPDATE = "APPFEEDBACKSTATUS_UPDATE";
export const APPFEEDBACKSTATUS_DELETE = "APPFEEDBACKSTATUS_DELETE";

// bước xử lý phản hồi
export const APPFEEDBACKSTEP_VIEW = "APPFEEDBACKSTEP_VIEW";
export const APPFEEDBACKSTEP_ADD = "APPFEEDBACKSTEP_ADD";
export const APPFEEDBACKSTEP_UPDATE = "APPFEEDBACKSTEP_UPDATE";
export const APPFEEDBACKSTEP_DELETE = "APPFEEDBACKSTEP_DELETE";

// Loại phản hồi ứng dụng
export const APPFEEDBACKTYPE_VIEW = "APPFEEDBACKTYPE_VIEW";
export const APPFEEDBACKTYPE_ADD = "APPFEEDBACKTYPE_ADD";
export const APPFEEDBACKTYPE_UPDATE = "APPFEEDBACKTYPE_UPDATE";
export const APPFEEDBACKTYPE_DELETE = "APPFEEDBACKTYPE_DELETE";

// cấu hình hệ thống TMS
export const TMSCONFIG_VIEW = "TMSCONFIG_VIEW";
export const TMSCONFIG_ADD = "TMSCONFIG_ADD";
export const TMSCONFIG_UPDATE = "TMSCONFIG_UPDATE";
export const TMSCONFIG_DELETE = "TMSCONFIG_DELETE";

// Lý do cập nhật giờ giao hàng
export const DELIVERYDATEUPDATEREASON_VIEW = "DELIVERYDATEUPDATEREASON_VIEW";
export const DELIVERYDATEUPDATEREASON_ADD = "DELIVERYDATEUPDATEREASON_ADD";
export const DELIVERYDATEUPDATEREASON_UPDATE = "DELIVERYDATEUPDATEREASON_UPDATE";
export const DELIVERYDATEUPDATEREASON_DELETE = "DELIVERYDATEUPDATEREASON_DELETE";

// Loại cập nhật giờ giao hàng
export const DELIVERYDATEUPDATETYPE_VIEW = "DELIVERYDATEUPDATETYPE_VIEW";
export const DELIVERYDATEUPDATETYPE_ADD = "DELIVERYDATEUPDATETYPE_ADD";
export const DELIVERYDATEUPDATETYPE_UPDATE = "DELIVERYDATEUPDATETYPE_UPDATE";
export const DELIVERYDATEUPDATETYPE_DELETE = "DELIVERYDATEUPDATETYPE_DELETE";

//Xem báo cáo vận đơn
export const SHIPMENTORDER_REPORT_VIEW = "SHIPMENTORDER_REPORT_VIEW";
//Xuất báo cáo vận đơn
export const SHIPMENTORDER_REPORT = "SHIPMENTORDER_REPORT";
export const TMS_STAFFDEBT_REPORT_VIEW = "TMS_STAFFDEBT_REPORT_VIEW";

//Xem báo cáo vận đơn của Trưởng nhóm
export const SHIPMENTORDER_REPORTCOORDINATORUSER_VIEW = "SHIPMENTORDER_REPORTCOORDINATORUSER_VIEW";

//Thưởng nhân viên
export const REWARD_VIEW = "REWARD_VIEW";
export const REWARDDETAIL_VIEW = "REWARDDETAIL_VIEW";

//Xem danh sách thưởng
export const TMS_TMSREWARD_VIEW = "TMS_TMSREWARD_VIEW";
export const TMS_TMSREWARD_SO_TYPE_VIEW = "TMS_TMSREWARD_SO_TYPE_VIEW";

//Báo cáo danh sách vận đơn không được tính thưởng
export const TMS_NOTREWARD_EXPORT = "TMS_NOTREWARD_EXPORT";

//Kiểm tra điểm thưởng
export const TMS_TMSREWARD_REVIEW = "TMS_TMSREWARD_REVIEW";
//Tính chi phí thưởng theo ngày
export const TMS_TMSREWARD_COMPUTE = "TMS_TMSREWARD_COMPUTE";
//Kiểm tra điểm thưởng theo nhân viên
export const TMS_TMSREWARD_BYUSERNAME = "TMS_TMSREWARD_BYUSERNAME";

//Xem danh sách báo cao công nợ
export const TMS_BEGINTERMADVANCEDEBT_VIEW = "TMS_BEGINTERMADVANCEDEBT_VIEW";

//Bảng lưu nợ tiền thu hộ của nhân viên
export const TMS_STAFFDEBT_VIEW = "TMS_STAFFDEBT_VIEW";
export const TMS_STAFFDEBT_UNLOCKDELIVERY = "TMS_STAFFDEBT_UNLOCKDELIVERY";
export const TMS_STAFFDEBTDETAIL_UNLOCKDELIVERY = "TMS_STAFFDEBTDETAIL_UNLOCKDELIVERY";

//Bảng Thông kê hạn mức tạm ứng
export const TMS_CURRENTADVANCEDEBT_VIEW = "TMS_CURRENTADVANCEDEBT_VIEW";

//Tra cứu trạng thái đơn hàng
export const TMS_INVESTIGATION_SO_STATUS = "TMS_INVESTIGATION_SO_STATUS";

//Bảng giá dịch vụ của đối tác
export const TMS_PNSERVICEPRICETABLE_VIEW = "TMS_PNSERVICEPRICETABLE_VIEW";
export const TMS_PNSERVICEPRICETABLE_ADD = "TMS_PNSERVICEPRICETABLE_ADD";
export const TMS_PNSERVICEPRICETABLE_UPDATE = "TMS_PNSERVICEPRICETABLE_UPDATE";
export const TMS_PNSERVICEPRICETABLE_DELETE = "TMS_PNSERVICEPRICETABLE_DELETE";

//Bảng giá dịch vụ của đối tác
export const TMS_PNSERVICEPRICETABLEDETAIL_VIEW = "TMS_PNSERVICEPRICETABLEDETAIL_VIEW";
export const TMS_PNSERVICEPRICETABLEDETAIL_ADD = "TMS_PNSERVICEPRICETABLEDETAIL_ADD";
export const TMS_PNSERVICEPRICETABLEDETAIL_UPDATE = "TMS_PNSERVICEPRICETABLEDETAIL_UPDATE";
export const TMS_PNSERVICEPRICETABLEDETAIL_DELETE = "TMS_PNSERVICEPRICETABLEDETAIL_DELETE";

//Yêu cầu nhập trả vật tư
export const TMS_MTRETURNREQUEST_VIEW = "TMS_MTRETURNREQUEST_VIEW";
export const TMS_MTRETURNREQUEST_ADD = "TMS_MTRETURNREQUEST_ADD";
export const TMS_MTRETURNREQUEST_UPDATE = "TMS_MTRETURNREQUEST_UPDATE";
export const TMS_MTRETURNREQUEST_DELETE = "TMS_MTRETURNREQUEST_DELETE";
export const TMS_MTRETURNREQUEST_EXPORT = "TMS_MTRETURNREQUEST_EXPORT";
export const TMS_MTRETURNREQUEST_CREATEDVOUCHER = "TMS_MTRETURNREQUEST_CREATEDVOUCHER";

//Nhóm tiêu chí đánh giá chất lượng
export const QUALITYASSESSGROUP_VIEW = "QUALITYASSESSGROUP_VIEW";
export const QUALITYASSESSGROUP_ADD = "QUALITYASSESSGROUP_ADD";
export const QUALITYASSESSGROUP_UPDATE = "QUALITYASSESSGROUP_UPDATE";
export const QUALITYASSESSGROUP_DELETE = "QUALITYASSESSGROUP_DELETE";

//Loại tiêu chí đánh giá chất lượng
export const QUALITYASSESSTYPE_VIEW = "QUALITYASSESSTYPE_VIEW";
export const QUALITYASSESSTYPE_ADD = "QUALITYASSESSTYPE_ADD";
export const QUALITYASSESSTYPE_UPDATE = "QUALITYASSESSTYPE_UPDATE";
export const QUALITYASSESSTYPE_DELETE = "QUALITYASSESSTYPE_DELETE";

// Lịch đồng bộ dữ liệu đánh giá vận đơn
export const SOASSESSSYNSCHEDULE_VIEW = "SOASSESSSYNSCHEDULE_VIEW";
export const SOASSESSSYNSCHEDULE_ADD = "SOASSESSSYNSCHEDULE_ADD";
export const SOASSESSSYNSCHEDULE_UPDATE = "SOASSESSSYNSCHEDULE_UPDATE";
export const SOASSESSSYNSCHEDULE_DELETE = "SOASSESSSYNSCHEDULE_DELETE";

// Tải giao hàng
export const DELIVERYABILITY_VIEW = "DELIVERYABILITY_VIEW";
export const DELIVERYABILITY_ADD = "DELIVERYABILITY_ADD";
export const DELIVERYABILITY_UPDATE = "DELIVERYABILITY_UPDATE";
export const DELIVERYABILITY_DELETE = "DELIVERYABILITY_DELETE";
export const DELIVERYABILITY_IMPORT = "DELIVERYABILITY_IMPORT";
export const DELIVERYABILITY_EXPORT = "DELIVERYABILITY_EXPORT";

// Danh sách nhóm hàng hóa vận chuyển
export const DELIVERYGOODSGROUP_VIEW = "DELIVERYGOODSGROUP_VIEW";
export const DELIVERYGOODSGROUP_ADD = "DELIVERYGOODSGROUP_ADD";
export const DELIVERYGOODSGROUP_UPDATE = "DELIVERYGOODSGROUP_UPDATE";
export const DELIVERYGOODSGROUP_DELETE = "DELIVERYGOODSGROUP_DELETE";

// Danh sách khung thời gian vận chuyển
export const DELIVERYTIMEFRAME_VIEW = "DELIVERYTIMEFRAME_VIEW";
export const DELIVERYTIMEFRAME_ADD = "DELIVERYTIMEFRAME_ADD";
export const DELIVERYTIMEFRAME_UPDATE = "DELIVERYTIMEFRAME_UPDATE";
export const DELIVERYTIMEFRAME_DELETE = "DELIVERYTIMEFRAME_DELETE";

// Danh sách các ngày trong tuần
export const WEEKDAY_VIEW = "WEEKDAY_VIEW";
export const WEEKDAY_ADD = "WEEKDAY_ADD";
export const WEEKDAY_UPDATE = "WEEKDAY_UPDATE";
export const WEEKDAY_DELETE = "WEEKDAY_DELETE";

// Nhóm điều phối
export const COORDINATORGROUP_VIEW = "COORDINATORGROUP_VIEW";
export const COORDINATORGROUP_ADD = "COORDINATORGROUP_ADD";
export const COORDINATORGROUP_UPDATE = "COORDINATORGROUP_UPDATE";
export const COORDINATORGROUP_DELETE = "COORDINATORGROUP_DELETE";
export const MDM_COORDINATORGROUP_EXPORT = "MDM_COORDINATORGROUP_EXPORT";

// Template tin nhắn SMS
export const SMSTEMPLATE_VIEW = "SMSTEMPLATE_VIEW";
export const SMSTEMPLATE_ADD = "SMSTEMPLATE_ADD";
export const SMSTEMPLATE_UPDATE = "SMSTEMPLATE_UPDATE";
export const SMSTEMPLATE_DELETE = "SMSTEMPLATE_DELETE";

// nhóm dịch vụ
export const SERVICEGROUP_VIEW = "SERVICEGROUP_VIEW";
export const SERVICEGROUP_ADD = "SERVICEGROUP_ADD";
export const SERVICEGROUP_UPDATE = "SERVICEGROUP_UPDATE";
export const SERVICEGROUP_DELETE = "SERVICEGROUP_DELETE";

//Xuất báo cáo vận đơn
export const SHIPMENTORDER_REPORT_EXPORT = "SHIPMENTORDER_REPORT_EXPORT";

//Xuất danh sách báo cao công nợ theo nhân viên
export const TMS_BEGINTERMADVANCEDEBT_EXPORT = "TMS_BEGINTERMADVANCEDEBT_EXPORT";

// Xuất danh sách quản lý công nợ
export const TMS_STAFFDEBT_EXPORT = "TMS_STAFFDEBT_EXPORT";

//xuất danh sách thưởng giao hàng
export const TMS_TMSREWARD_EXPORT = "TMS_TMSREWARD_EXPORT";

// xuất danh sách thưởng giao hàng theo loại
export const TMS_TMSREWARD_SO_TYPE_EXPORT = "TMS_TMSREWARD_SO_TYPE_EXPORT";

//xuất danh sách hợp đồng dịch vụ
export const SERVICEAGREEMENT_EXPORT = "SERVICEAGREEMENT_EXPORT";

// xuất danh sách chi tiết tiền phải trả cho nhà cung cấp dịch vụ
export const PARTNERPAYABLEDETAIL_EXPORT = "PARTNERPAYABLEDETAIL_EXPORT";

// xuất danh sách yêu cầu tạm ứng
export const ADVANCEREQUEST_EXPORT = "ADVANCEREQUEST_EXPORT";

//xuất danh sách yêu cầu hủy vật tư
export const DESTROYREQUEST_EXPORT = "DESTROYREQUEST_EXPORT";

// xuất danh sách yêu cầu kiểm kê
export const INVENTORYREQUEST_EXPORT = "INVENTORYREQUEST_EXPORT";

// xuất thống kê hạn mức tạm ứng
export const TMS_CURRENTADVANCEDEBT_EXPORT = "TMS_CURRENTADVANCEDEBT_EXPORT";

//xuất danh sách loại đối tác
export const PARTNERTYPE_EXPORT = "PARTNERTYPE_EXPORT";

//xuất danh sách đối tác
export const PARTNER_EXPORT = "PARTNER_EXPORT";

// xuất danh sách lý do hủy giao hàng
export const CANCELDELIVERYREASON_EXPORT = "CANCELDELIVERYREASON_EXPORT";

// xuất danh sách loại phương tiện vận chuyển
export const CARRIERTYPE_EXPORT = "CARRIERTYPE_EXPORT";

// xuất danh sách loại đóng gói hàng hóa vận chuyển
export const PACKAGETYPE_EXPORT = "PACKAGETYPE_EXPORT";

// xuất danh sách phương thức thanh toán chi phí vận chuyển
export const SHIPMENTFEEPAYMENTMETHOD_EXPORT = "SHIPMENTFEEPAYMENTMETHOD_EXPORT";

// xuất danh sách loại dịch vụ vận chuyển
export const SHIPMENTSERVICETYPE_EXPORT = "SHIPMENTSERVICETYPE_EXPORT";

// xuất danh sách loại hàng hóa vận chuyển
export const SHIPMENTGOODSTYPE_EXPORT = "SHIPMENTGOODSTYPE_EXPORT";

// xuất nhóm trạng thái yêu cầu vận chuyển
export const SHIPMENTORDERSTATUSGROUP_EXPORT = "SHIPMENTORDERSTATUSGROUP_EXPORT";

// xuất trạng thái yêu cầu vận chuyển
export const SHIPMENTORDERSTATUS_EXPORT = "SHIPMENTORDERSTATUS_EXPORT";

// xuất danh sách loại phí vận chuyển
export const SHIPMENTFEETYPE_EXPORT = "SHIPMENTFEETYPE_EXPORT";

//xuất danh sách vị trí thưởng của nhân viên
export const USER_REWARDPOSITION_EXPORT = "USER_REWARDPOSITION_EXPORT";

// xuất dịnh nghĩa kho điều phối giao hàng
export const COORDINATORSTORE_EXPORT = "COORDINATORSTORE_EXPORT";

// xuất danh sách vị trí thưởng theo khoảng thời gian
export const PERIODUSERRWPOSITION_EXPORT = "PERIODUSERRWPOSITION_EXPORT";

// Danh sách bảng giá dịch vụ của Tận Tâm
export const SERVICEPRICETABLE_VIEW = "SERVICEPRICETABLE_VIEW";
export const SERVICEPRICETABLE_ADD = "SERVICEPRICETABLE_ADD";
export const SERVICEPRICETABLE_UPDATE = "SERVICEPRICETABLE_UPDATE";
export const SERVICEPRICETABLE_DELETE = "SERVICEPRICETABLE_DELETE";

// Danh sách bảng giá dịch vụ chi tiết của Tận Tâm
export const SERVICEPRICETABLEDETAIL_VIEW = "SERVICEPRICETABLEDETAIL_VIEW";
export const SERVICEPRICETABLEDETAIL_ADD = "SERVICEPRICETABLEDETAIL_ADD";
export const SERVICEPRICETABLEDETAIL_UPDATE = "SERVICEPRICETABLEDETAIL_UPDATE";
export const SERVICEPRICETABLEDETAIL_DELETE = "SERVICEPRICETABLEDETAIL_DELETE";

// Danh sách bảng giá dịch vụ khu vực của Tận Tâm
export const SERVICEPRICETABLEAREA_VIEW = "SERVICEPRICETABLE_VIEW";
export const SERVICEPRICETABLEAREA_ADD = "SERVICEPRICETABLE_ADD";
export const SERVICEPRICETABLEAREA_UPDATE = "SERVICEPRICETABLE_UPDATE";
export const SERVICEPRICETABLEAREA_DELETE = "SERVICEPRICETABLE_DELETE";

// Kênh bán hàng của đối tác
export const PARTNERSALECHANNEL_VIEW = "PARTNERSALECHANNEL_VIEW";
export const PARTNERSALECHANNEL_ADD = "PARTNERSALECHANNEL_ADD";
export const PARTNERSALECHANNEL_UPDATE = "PARTNERSALECHANNEL_UPDATE";
export const PARTNERSALECHANNEL_DELETE = "PARTNERSALECHANNEL_DELETE";

// Báo cáo đối soát
export const CROSSCHECKREPORT_VIEW = "CROSSCHECKREPORT_VIEW";
export const CROSSCHECKDETAILREPORT_VIEW = "CROSSCHECKDETAILREPORT_VIEW";

// Template xuất dữ liệu
export const DATAEXPORTTEMPLATE_VIEW = "DATAEXPORTTEMPLATE_VIEW";
export const DATAEXPORTTEMPLATE_ADD = "DATAEXPORTTEMPLATE_ADD";
export const DATAEXPORTTEMPLATE_UPDATE = "DATAEXPORTTEMPLATE_UPDATE";
export const DATAEXPORTTEMPLATE_DELETE = "DATAEXPORTTEMPLATE_DELETE";

// Bảng chuyển đổi thời gian thực hiện dịch vụ sang sản phẩm dịch vụ
export const SVTIMECONVERT_VIEW = "SVTIMECONVERT_VIEW";
export const SVTIMECONVERT_ADD = "SVTIMECONVERT_ADD";
export const SVTIMECONVERT_UPDATE = "SVTIMECONVERT_UPDATE";
export const SVTIMECONVERT_DELETE = "SVTIMECONVERT_DELETE";

//Loại tính thưởng
export const REWARDCOMPUTETYPE_VIEW = "REWARDCOMPUTETYPE_VIEW";
export const REWARDCOMPUTETYPE_ADD = "REWARDCOMPUTETYPE_ADD";
export const REWARDCOMPUTETYPE_UPDATE = "REWARDCOMPUTETYPE_UPDATE";
export const REWARDCOMPUTETYPE_DELETE = "REWARDCOMPUTETYPE_DELETE";

//Danh sách tính thưởng
export const TMS_REWARDCOMPUTELIST_VIEW = "TMS_REWARDCOMPUTELIST_VIEW";
export const TMS_REWARDCOMPUTELIST_CONFIRM = "TMS_REWARDCOMPUTELIST_CONFIRM";

// Loại hình thuyên chuyển nhân viên
export const STAFFTRANSFERTYPE_VIEW = "STAFFTRANSFERTYPE_VIEW";
export const STAFFTRANSFERTYPE_DELETE = "STAFFTRANSFERTYPE_DELETE";
export const STAFFTRANSFERTYPE_ADD = "STAFFTRANSFERTYPE_ADD";
export const STAFFTRANSFERTYPE_UPDATE = "STAFFTRANSFERTYPE_UPDATE";

// Thuyên chuyển nhân viên
export const STAFFTRANSFER_ADD = "STAFFTRANSFER_ADD";
export const STAFFTRANSFER_VIEW = "STAFFTRANSFER_VIEW";
export const STAFFTRANSFERID_DELETE = "STAFFTRANSFERID_DELETE";
export const STAFFTRANSFERID_EXPORT = "STAFFTRANSFERID_EXPORT";
export const STAFFTRANSFERID_UPDATE = "STAFFTRANSFERID_UPDATE";

// Tài liệu
export const DOCUMENT_VIEW = "DOCUMENT_VIEW";
export const DOCUMENT_DELETE = "DOCUMENT_DELETE";
export const DOCUMENT_ADD = "DOCUMENT_ADD";
export const DOCUMENT_UPDATE = "DOCUMENT_UPDATE";
export const DOCUMENT_PUBLISHED = "DOCUMENT_PUBLISHED";

//Bảng lưu khoảng thời gian nhân viên được phụ cấp xăng
export const FUELSUBSIDIZEPERIOD_VIEW = "FUELSUBSIDIZEPERIOD_VIEW";
export const FUELSUBSIDIZEPERIOD_ADD = "FUELSUBSIDIZEPERIOD_ADD";
export const FUELSUBSIDIZEPERIOD_DEL = "FUELSUBSIDIZEPERIOD_DEL";
export const FUELSUBSIDIZEPERIOD_EXPORT = "FUELSUBSIDIZEPERIOD_EXPORT";

// Bảng khai báo hạn mức công nợ theo nhân viên
export const USERDEBTLIMIT_VIEW = "USERDEBTLIMIT_VIEW";
export const USERDEBTLIMIT_ADD = "USERDEBTLIMIT_ADD";
export const USERDEBTLIMIT_UPDATE = "USERDEBTLIMIT_UPDATE";
export const USERDEBTLIMIT_DELETE = "USERDEBTLIMIT_DELETE";

// Danh sách các khung giờ của một ca làm việc
export const WORKINGSHIFTTIMEFRAME_VIEW = "WORKINGSHIFTTIMEFRAME_VIEW";
export const WORKINGSHIFTTIMEFRAME_ADD = "WORKINGSHIFTTIMEFRAME_ADD";
export const WORKINGSHIFTTIMEFRAME_UPDATE = "WORKINGSHIFTTIMEFRAME_UPDATE";
export const WORKINGSHIFTTIMEFRAME_DELETE = "WORKINGSHIFTTIMEFRAME_DELETE";

//Yêu cầu hoàn trả vật tư
export const MATERIALRECLAIM_VIEW = "MATERIALRECLAIM_VIEW";
export const MATERIALRECLAIM_ADD = "MATERIALRECLAIM_ADD";
export const MATERIALRECLAIM_UPDATE = "MATERIALRECLAIM_UPDATE";
export const MATERIALRECLAIM_DELETE = "MATERIALRECLAIM_DELETE";
export const MATERIALRECLAIM_EXPORT = "MATERIALRECLAIM_EXPORT";
export const TMS_MATERIALRECLAIM_RETURN = "TMS_MATERIALRECLAIM_RETURN";
export const TMS_MATERIALRECLAIM_DESTROY = "TMS_MATERIALRECLAIM_DESTROY";

//Yêu cầu nhập trả xác linh kiện về kho
export const TMS_MATERIALRETURN_VIEW = 'TMS_MATERIALRETURNDETAIL_VIEW';
export const TMS_MATERIALRETURN_RETURN = 'TMS_MATERIALRETURN_RETURN';

//Quản lý yêu cầu thuê xe 
export const TMS_VEHICLERENTALREQUEST_VIEW = 'TMS_VEHICLERENTALREQUEST_VIEW';
export const TMS_VEHICLERENTALREQUEST_ADD = 'TMS_VEHICLERENTALREQUEST_ADD';
export const TMS_VEHICLERENTALREQUEST_UPDATE = 'TMS_VEHICLERENTALREQUEST_UPDATE';
export const TMS_VEHICLERENTALREQUEST_DELETE = 'TMS_VEHICLERENTALREQUEST_DELETE';
export const TMS_VEHICLERENTALREQUEST_ADDABILITY = 'TMS_VEHICLERENTALREQUEST_ADDABILITY';
export const TMS_VEHICLERENTALREQUEST_ADDFEE = 'TMS_VEHICLERENTALREQUEST_ADDFEE';

// Khai báo model xe
export const MD_VEHICLEMODEL_VIEW = "MD_VEHICLEMODEL_VIEW";
export const MD_VEHICLEMODEL_ADD = "MD_VEHICLEMODEL_ADD";
export const MD_VEHICLEMODEL_UPDATE = "MD_VEHICLEMODEL_UPDATE";
export const MD_VEHICLEMODEL_DELETE = "MD_VEHICLEMODEL_DELETE";


// khai báo lỗi thực tế
export const SYMPTOM_VIEW = "SYMPTOM_VIEW";
export const SYMPTOM_ADD = "SYMPTOM_ADD";
export const SYMPTOM_UPDATE = "SYMPTOM_UPDATE";
export const SYMPTOM_DELETE = "SYMPTOM_DELETE";

//Doanh thu xây dựng bảo trỉ
export const MAINTAINCONSTRUCT_VIEW = "MAINTAINCONSTRUCT_VIEW";
export const MAINTAINCONSTRUCT_ADD = "MAINTAINCONSTRUCT_ADD";
export const MAINTAINCONSTRUCT_UPDATE = "MAINTAINCONSTRUCT_UPDATE";
export const MAINTAINCONSTRUCT_DELETE = "MAINTAINCONSTRUCT_DELETE";

// Báo cáo quỹ thưởng trưởng nhóm
export const TMS_TEAMLEADERBONUSFUNDREPORT_EXPORT = "TMS_TEAMLEADERBONUSFUNDREPORT_EXPORT";

// Báo cáo nhập trả trên TMS
export const TMSSORETURNITEMREPORT_VIEW = "TMSSORETURNITEMREPORT_VIEW";
export const TMSSORETURNITEMREPORT_EXPORT = "TMSSORETURNITEMREPORT_EXPORT";

// Mối bán hàng
export const LEADORDER_VIEW = "LEADORDER_VIEW";

// Danh mục sản phẩm tư vấn ứng với loại yêu cầu vận chuyển (cùng loại)
export const MD_LEADADVICE_VIEW = "MD_LEADADVICE_VIEW";
export const MD_LEADADVICE_ADD = "MD_LEADADVICE_ADD";
export const MD_LEADADVICE_UPDATE = "MD_LEADADVICE_UPDATE";
export const MD_LEADADVICE_DELETE = "MD_LEADADVICE_DELETE";

// Danh mục sản phẩm tư vấn ứng với loại yêu cầu vận chuyển (khác loại)
export const MD_LEADADVICEAPPLY_VIEW = "MD_LEADADVICEAPPLY_VIEW";
export const MD_LEADADVICEAPPLY_ADD = "MD_LEADADVICEAPPLY_ADD";
export const MD_LEADADVICEAPPLY_UPDATE = "MD_LEADADVICEAPPLY_UPDATE";
export const MD_LEADADVICEAPPLY_DELETE = "MD_LEADADVICEAPPLY_DELETE";

// Danh sách lý do tư vấn thất bại
export const MD_FAILADVICEREASON_VIEW = "MD_FAILADVICEREASON_VIEW";
export const MD_FAILADVICEREASON_ADD = "MD_FAILADVICEREASON_ADD";
export const MD_FAILADVICEREASON_UPDATE = "MD_FAILADVICEREASON_UPDATE";
export const MD_FAILADVICEREASON_DELETE = "MD_FAILADVICEREASON_DELETE";

// Danh sách Loại mối bán hàng
export const MD_LEADORDERTYPE_VIEW = "MD_LEADORDERTYPE_VIEW";
export const MD_LEADORDERTYPE_ADD = "MD_LEADORDERTYPE_ADD";
export const MD_LEADORDERTYPE_UPDATE = "MD_LEADORDERTYPE_UPDATE";
export const MD_LEADORDERTYPE_DELETE = "MD_LEADORDERTYPE_DELETE";

// Danh sách Phương thức xử lý của mối bán hàng
export const MD_LEADORDERTYPEPROCESS_VIEW = "MD_LEADORDERTYPEPROCESS_VIEW";
export const MD_LEADORDERTYPEPROCESS_ADD = "MD_LEADORDERTYPEPROCESS_ADD";
export const MD_LEADORDERTYPEPROCESS_UPDATE = "MD_LEADORDERTYPEPROCESS_UPDATE";
export const MD_LEADORDERTYPEPROCESS_DELETE = "MD_LEADORDERTYPEPROCESS_DELETE";

// Danh sách Trạng thái của mối bán hàng
export const MD_LEADORDERSTATUS_VIEW = "MD_LEADORDERSTATUS_VIEW";
export const MD_LEADORDERSTATUS_ADD = "MD_LEADORDERSTATUS_ADD";
export const MD_LEADORDERSTATUS_UPDATE = "MD_LEADORDERSTATUS_UPDATE";
export const MD_LEADORDERSTATUS_DELETE = "MD_LEADORDERSTATUS_DELETE";

// Danh sách Bước xử lý của mối bán hàng
export const MD_LEADORDERSTEP_VIEW = "MD_LEADORDERSTEP_VIEW";
export const MD_LEADORDERSTEP_ADD = "MD_LEADORDERSTEP_ADD";
export const MD_LEADORDERSTEP_UPDATE = "MD_LEADORDERSTEP_UPDATE";
export const MD_LEADORDERSTEP_DELETE = "MD_LEADORDERSTEP_DELETE";

//Bước trả xác linh kiện cho hãng
export const MD_MTOUTPUTREQUESTSTEP_VIEW = "MD_MTOUTPUTREQUESTSTEP_VIEW";
export const MD_MTOUTPUTREQUESTSTEP_ADD = "MD_MTOUTPUTREQUESTSTEP_ADD";
export const MD_MTOUTPUTREQUESTSTEP_UPDATE = "MD_MTOUTPUTREQUESTSTEP_UPDATE";
export const MD_MTOUTPUTREQUESTSTEP_DELETE = "MD_MTOUTPUTREQUESTSTEP_DELETE";

// danh sách trạng thái trả xác linh kiện cho hãng
export const MD_MTOUTPUTREQUESTSTATUS_VIEW = "MD_MTOUTPUTREQUESTSTATUS_VIEW";
export const MD_MTOUTPUTREQUESTSTATUS_ADD = "MD_MTOUTPUTREQUESTSTATUS_ADD";
export const MD_MTOUTPUTREQUESTSTATUS_UPDATE = "MD_MTOUTPUTREQUESTSTATUS_UPDATE";
export const MD_MTOUTPUTREQUESTSTATUS_DELETE = "MD_MTOUTPUTREQUESTSTATUS_DELETE";

// danh sách loại yêu cầu trả xác linh kiện cho hãng
export const MD_MTOUTPUTREQUESTTYPE_VIEW = "MD_MTOUTPUTREQUESTTYPE_VIEW";
export const MD_MTOUTPUTREQUESTTYPE_ADD = "MD_MTOUTPUTREQUESTTYPE_ADD";
export const MD_MTOUTPUTREQUESTTYPE_UPDATE = "MD_MTOUTPUTREQUESTTYPE_UPDATE";
export const MD_MTOUTPUTREQUESTTYPE_DELETE = "MD_MTOUTPUTREQUESTTYPE_DELETE";

// thông tin hãng nhận xác linh kiện
export const MD_MTBRANDDELIVERYADDRESS_VIEW = "MD_MTBRANDDELIVERYADDRESS_VIEW";
export const MD_MTBRANDDELIVERYADDRESS_ADD = "MD_MTBRANDDELIVERYADDRESS_ADD";
export const MD_MTBRANDDELIVERYADDRESS_UPDATE = "MD_MTBRANDDELIVERYADDRESS_UPDATE";
export const MD_MTBRANDDELIVERYADDRESS_DELETE = "MD_MTBRANDDELIVERYADDRESS_DELETE";

// thông báo
export const NOTIFY_VIEW = "NOTIFY_VIEW";
export const NOTIFY_ADD = "NOTIFY_ADD";
export const NOTIFY_UPDATE = "NOTIFY_UPDATE";
export const NOTIFY_DELETE = "NOTIFY_DELETE"; 

// hạng mục công việc
export const SHIPMENTORDERTASK_VIEW = "SHIPMENTORDERTASK_VIEW";
export const SHIPMENTORDERTASK_ADD = "SHIPMENTORDERTASK_ADD";
export const SHIPMENTORDERTASK_UPDATE = "SHIPMENTORDERTASK_UPDATE";
export const SHIPMENTORDERTASK_DELETE = "SHIPMENTORDERTASK_DELETE"; 

// Quyền tạo yêu cầu trả xác
export const TMS_MTOUTPUTREQUEST_CREATE = "TMS_MTOUTPUTREQUEST_CREATE";
// Quyền xem danh sách yêu cầu trả xác linh kiện
export const TMS_MTOUTPUTREQUEST_VIEW = "TMS_MTOUTPUTREQUEST_VIEW";
//Quyền xác nhận
export const TMS_MTOUTPUTREQUEST_FEEDBACK = "TMS_MTOUTPUTREQUEST_FEEDBACK";
//Quyền duyệt
export const TMS_MTOUTPUTREQUEST_REVIEW = "TMS_MTOUTPUTREQUEST_REVIEW";

// Quyền thêm danh sách loại danh mục dịch vụ
export const SVCATEGORYTYPE_VIEW = "SVCATEGORYTYPE_VIEW";
export const SVCATEGORYTYPE_ADD = "SVCATEGORYTYPE_ADD";
export const SVCATEGORYTYPE_UPDATE = "SVCATEGORYTYPE_UPDATE";
export const SVCATEGORYTYPE_DELETE = "SVCATEGORYTYPE_DELETE";

// Quyền thêm danh mục dịch vụ
export const SVCATEGORY_VIEW = "SVCATEGORY_VIEW";
export const SVCATEGORY_ADD = "SVCATEGORY_ADD";
export const SVCATEGORY_UPDATE = "SVCATEGORY_UPDATE";
export const SVCATEGORY_DELETE = "SVCATEGORY_DELETE"; 

// Công trình
export const MP_PROJECT_VIEW = "MP_PROJECT_VIEW"; 

// Công trình nâng cấp
export const MP_PROJECT_UPGRADE_VIEW = "MP_PROJECT_UPGRADE_VIEW"; 
// Đánh giá chất lượng giao hàng
export const SHIPMENTQUALITYASSESS_VIEW = "SHIPMENTQUALITYASSESS_VIEW"; 

// loại đơn giá điểm thưởng theo khoảng thời gian
export const TMS_PERIODREWARDPRICETYPE_VIEW = "TMS_PERIODREWARDPRICETYPE_VIEW";
export const TMS_PERIODREWARDPRICETYPE_ADD = "TMS_PERIODREWARDPRICETYPE_ADD";
export const TMS_PERIODREWARDPRICETYPE_UPDATE = "TMS_PERIODREWARDPRICETYPE_UPDATE";
export const TMS_PERIODREWARDPRICETYPE_DELETE = "TMS_PERIODREWARDPRICETYPE_DELETE"; 

// đơn giá thưởng theo khoảng thời gian
export const TMS_PERIODREWARDPRICE_VIEW = "TMS_PERIODREWARDPRICE_VIEW";
export const TMS_PERIODREWARDPRICE_ADD = "TMS_PERIODREWARDPRICE_ADD";
export const TMS_PERIODREWARDPRICE_UPDATE = "TMS_PERIODREWARDPRICE_UPDATE";
export const TMS_PERIODREWARDPRICE_DELETE = "TMS_PERIODREWARDPRICE_DELETE"; 

//Quyền thêm vận đơn cho công trình Cấp cho TP trở lên 

export const TMS_SHIPMENTORDERPROJECT_ADD = "TMS_SHIPMENTORDERPROJECT_ADD";


// Danh sách loại yêu cầu vận chuyển áp dụng bảng giá này
export const TMS_REWARDPRICETABLE_SOTYPE_VIEW = "TMS_REWARDPRICETABLE_SOTYPE_VIEW";
export const TMS_REWARDPRICETABLE_SOTYPE_ADD = "TMS_REWARDPRICETABLE_SOTYPE_ADD";
export const TMS_REWARDPRICETABLE_SOTYPE_UPDATE = "TMS_REWARDPRICETABLE_SOTYPE_UPDATE";
export const TMS_REWARDPRICETABLE_SOTYPE_DELETE = "TMS_REWARDPRICETABLE_SOTYPE_DELETE"; 


// Loại thay đổi địa chỉ giao hàng
export const CHANGEDELIVERYADDRESSTYPE_VIEW = "CHANGEDELIVERYADDRESSTYPE_VIEW";
export const CHANGEDELIVERYADDRESSTYPE_ADD = "CHANGEDELIVERYADDRESSTYPE_ADD";
export const CHANGEDELIVERYADDRESSTYPE_UPDATE = "CHANGEDELIVERYADDRESSTYPE_UPDATE";
export const CHANGEDELIVERYADDRESSTYPE_DELETE = "CHANGEDELIVERYADDRESSTYPE_DELETE"; 

// danh sách gói linh kiện
export const COMPONENTBUNDLE_VIEW = "COMPONENTBUNDLE_VIEW";
export const COMPONENTBUNDLE_DELETE = "COMPONENTBUNDLE_DELETE";
export const COMPONENTBUNDLE_ADD = "COMPONENTBUNDLE_ADD";
export const COMPONENTBUNDLE_UPDATE = "COMPONENTBUNDLE_UPDATE";

// danh sách gói linh kiện sản phẩm áp dụng
export const COMPONENTBUNDLE_PRODUCT_VIEW = "COMPONENTBUNDLE_PRODUCT_VIEW";
export const COMPONENTBUNDLE_PRODUCT_DELETE = "COMPONENTBUNDLE_PRODUCT_DELETE";
export const COMPONENTBUNDLE_PRODUCT_ADD = "COMPONENTBUNDLE_PRODUCT_ADD";
export const COMPONENTBUNDLE_PRODUCT_UPDATE = "COMPONENTBUNDLE_PRODUCT_UPDATE";

// Trạng thái gói linh kiện
export const MTSPLITREQUESTSTATUS_VIEW = "MTSPLITREQUESTSTATUS_VIEW";
export const MTSPLITREQUESTSTATUS_DELETE = "MTSPLITREQUESTSTATUS_DELETE";
export const MTSPLITREQUESTSTATUS_ADD = "MTSPLITREQUESTSTATUS_ADD";
export const MTSPLITREQUESTSTATUS_UPDATE = "MTSPLITREQUESTSTATUS_UPDATE";

// Bước xử lý
export const MTSPLITREQUESTSTEP_VIEW = "MTSPLITREQUESTSTEP_VIEW";
export const MTSPLITREQUESTSTEP_DELETE = "MTSPLITREQUESTSTEP_DELETE";
export const MTSPLITREQUESTSTEP_ADD = "MTSPLITREQUESTSTEP_ADD";
export const MTSPLITREQUESTSTEP_UPDATE = "MTSPLITREQUESTSTEP_UPDATE";

// Loại phân tích linh kiện
export const MTSPLITREQUESTTYPE_VIEW = "MTSPLITREQUESTTYPE_VIEW";
export const MTSPLITREQUESTTYPE_DELETE = "MTSPLITREQUESTTYPE_DELETE";
export const MTSPLITREQUESTTYPE_ADD = "MTSPLITREQUESTTYPE_ADD";
export const MTSPLITREQUESTTYPE_UPDATE = "MTSPLITREQUESTTYPE_UPDATE";

// yêu cầu rã xác linh kiện
export const MTSPLITREQUEST_VIEW = "MTSPLITREQUEST_VIEW";
export const MTSPLITREQUEST_DELETE = "MTSPLITREQUEST_DELETE";
export const MTSPLITREQUEST_ADD = "MTSPLITREQUEST_ADD";
export const MTSPLITREQUEST_UPDATE = "MTSPLITREQUEST_UPDATE";
export const MTSPLITREQUEST_CREATEDINPUTVOUCHER = "MTSPLITREQUEST_CREATEDINPUTVOUCHERs";

// danh sách yêu cầu ghi nhận sự cố vận chuyển
export const SHIPMENTORDER_INCIDENT_VIEW = "SHIPMENTORDER_INCIDENT_VIEW";
export const SHIPMENTORDER_INCIDENT_DELETE = "SHIPMENTORDER_INCIDENT_DELETE";
export const SHIPMENTORDER_INCIDENT_ADD = "SHIPMENTORDER_INCIDENT_ADD";
export const SHIPMENTORDER_INCIDENT_UPDATE = "SHIPMENTORDER_INCIDENT_UPDATE";

// danh sách thu hộ
export const BEHAFTCOLLECTION_VIEW = "BEHAFTCOLLECTION_VIEW";

// danh sách loại thu hộ
export const BEHAFTCOLLECTIONTYPE_VIEW = "BEHAFTCOLLECTIONTYPE_VIEW";
export const BEHAFTCOLLECTIONTYPE_DELETE = "BEHAFTCOLLECTIONTYPE_DELETE";
export const BEHAFTCOLLECTIONTYPE_ADD = "BEHAFTCOLLECTIONTYPE_ADD";
export const BEHAFTCOLLECTIONTYPE_UPDATE = "BEHAFTCOLLECTIONTYPE_UPDATE";

// danh sách phản hồi ứng dụng
export const APPFEEDBACK_VIEW = "APPFEEDBACK_VIEW";
export const APPFEEDBACK_DELETE = "APPFEEDBACK_DELETE";
export const APPFEEDBACK_ADD = "APPFEEDBACK_ADD";
export const APPFEEDBACK_UPDATE = "APPFEEDBACK_UPDATE";
// Xem tất cả danh sách phản hồi ứng dụng
export const APPFEEDBACK_VIEW_ALL = "APPFEEDBACK_VIEW_ALL";


// danh sách bình luận phản hồi 
export const EO_APPFEEDBACK_COMMENT_VIEW = "EO_APPFEEDBACK_COMMENT_VIEW";
export const EO_APPFEEDBACK_COMMENT_DELETE = "EO_APPFEEDBACK_COMMENT_DELETE";
export const EO_APPFEEDBACK_COMMENT_ADD = "EO_APPFEEDBACK_COMMENT_ADD";
export const EO_APPFEEDBACK_COMMENT_UPDATE = "EO_APPFEEDBACK_COMMENT_UPDATE";

// danh sách đính kèm tập tin phản hồi 
export const EO_APPFEEDBACK_ATTACHMENT_VIEW = "EO_APPFEEDBACK_ATTACHMENT_VIEW";
export const EO_APPFEEDBACK_ATTACHMENT_DELETE = "EO_APPFEEDBACK_ATTACHMENT_DELETE";
export const EO_APPFEEDBACK_ATTACHMENT_ADD = "EO_APPFEEDBACK_ATTACHMENT_ADD";
export const EO_APPFEEDBACK_ATTACHMENT_UPDATE = "EO_APPFEEDBACK_ATTACHMENT_UPDATE";
 
// quyền chuyển bước phản hồi 
export const APPFEEDBACKTYPE_WF_NEXT_UPDATE = "APPFEEDBACKTYPE_WF_NEXT_UPDATE";

// danh sách sự cố khi thực hiện cuộc gọi
export const PHONECALLINCIDENT_VIEW = "PHONECALLINCIDENT_VIEW";
export const PHONECALLINCIDENT_ADD = "PHONECALLINCIDENT_ADD";
export const PHONECALLINCIDENT_DELETE = "PHONECALLINCIDENT_DELETE";
export const PHONECALLINCIDENT_UPDATE = "PHONECALLINCIDENT_UPDATE";


// loại yêu cầu bổ sung vật tư
export const MTEXTOUTPUTREQUESTTYPE_VIEW = "MTEXTOUTPUTREQUESTTYPE_VIEW";
export const MTEXTOUTPUTREQUESTTYPE_ADD = "MTEXTOUTPUTREQUESTTYPE_ADD";
export const MTEXTOUTPUTREQUESTTYPE_UPDATE = "MTEXTOUTPUTREQUESTTYPE_UPDATE";
export const MTEXTOUTPUTREQUESTTYPE_DELETE = "MTEXTOUTPUTREQUESTTYPE_DELETE";


// Danh sách cấp bậc kỹ năng của một nhân viên
export const SYS_USER_SKILLRANK_VIEW = "SYS_USER_SKILLRANK_VIEW";
export const SYS_USER_SKILLRANK_ADD = "SYS_USER_SKILLRANK_ADD";
export const SYS_USER_SKILLRANK_UPDATE = "SYS_USER_SKILLRANK_UPDATE";
export const SYS_USER_SKILLRANK_DELETE = "SYS_USER_SKILLRANK_DELETE";

// Danh sách hạng khách víp
export const MEMBERSHIPRANKTMS_VIEW = "MEMBERSHIPRANKTMS_VIEW";
export const MEMBERSHIPRANKTMS_DELETE = "MEMBERSHIPRANKTMS_DELETE";
export const MEMBERSHIPRANKTMS_ADD = "MEMBERSHIPRANKTMS_ADD";
export const MEMBERSHIPRANKTMS_UPDATE = "MEMBERSHIPRANKTMS_UPDATE";

// Danh sách thành viên VIP
export const MEMBERSHIP_VIEW = "MEMBERSHIP_VIEW";
export const MEMBERSHIP_DELETE = "MEMBERSHIP_DELETE";
export const MEMBERSHIP_ADD = "MEMBERSHIP_ADD";
export const MEMBERSHIP_UPDATE = "MEMBERSHIP_UPDATE";
export const MEMBERSHIP_IMPORT = "MEMBERSHIP_IMPORT";

//Quyền xem lịch sử bảo trì siêu thị 
export const STOREMAINTENANCEHISTORY_VIEW = "STOREMAINTENANCEHISTORY_VIEW";
